//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JobBoard.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Job
    {
        public int JobId { get; set; }
        public string Job_title { get; set; }
        public string Job_type { get; set; }
        public string Description { get; set; }
        public Nullable<int> ReId { get; set; }
    
        public virtual Recruiter Recruiter { get; set; }
    }
}
